defaults:
  - _self_
  - override hydra/sweeper: optuna
  - override hydra/sweeper/sampler: tpe

cuda_visible_devices: 0

project_name: sequential_recsys/generation_paper/hyper/${task_name}
task_name: BERT4Rec_train_predict

optuna_metrics: val_ndcg@10


data_path: ../data/ml-20m.csv
last_n_items: 10

dataset:
  max_length: 128
  mlm_probability: 0.2
  force_last_item_masking_prob: 0

dataloader:
  batch_size: 64
  test_batch_size: 16
  num_workers: 8
  validation_size: 10000

model: 'BERT4Rec'
model_params:
  vocab_size: 2
  max_position_embeddings: 256
  hidden_size: 64
  num_hidden_layers: 2
  num_attention_heads: 2
  intermediate_size: 256
  attention_probs_dropout_prob: ${pdrop}
  hidden_dropout_prob: ${pdrop}

pdrop: 0.1

hydra:
  sweeper:
    sampler:
      _target_: optuna.samplers.TPESampler
    direction: maximize
    study_name: ${task_name}
    storage: "sqlite:///${task_name}.db"
    n_trials: 25
    n_jobs: 1
    params:
      model_params.hidden_size: choice(32, 64, 128, 256)
      model_params.num_hidden_layers: range(1, 3, step=1)
      model_params.num_attention_heads: choice(1, 2, 4)
      seqrec_module.lr: tag(log, interval(0.0003, 0.003))
      dataset.mlm_probability: range(0.1, 0.3, step=0.1)
      pdrop: choice(0.1, 0.3, 0.5)

seqrec_module:
  lr: 0.001
  predict_top_k: 10  # this value is used for validation
  filter_seen: True

trainer_params:
  max_epochs: 200

patience: 20

evaluator:
  top_k: [10]
test_metrics: False