defaults:
  - _self_
  - override hydra/sweeper: optuna
  - override hydra/sweeper/sampler: tpe

cuda_visible_devices: 0

project_name: sequential_recsys/generation_paper/hyper/${task_name}
task_name: GPT
seed: 17

optuna_metrics: val_ndcg@10

data_path: ../data/ml-20m.csv
last_n_items: 10

dataset:
  max_length: 128
  shift_labels: False

dataloader:
  batch_size: 32
  test_batch_size: 16
  num_workers: 8
  validation_size: 10000

model: 'GPT-2'

pdrop: 0.1
model_params:
  n_positions: ${dataset.max_length}
  n_embd: 256
  n_layer: 3
  n_head: 4
  embd_pdrop: ${pdrop}
  attn_pdrop: ${pdrop}  

hydra:
  sweeper:
    sampler:
      _target_: optuna.samplers.TPESampler
    direction: maximize
    study_name: ${task_name}
    storage: "sqlite:///${task_name}.db"
    n_trials: 50
    n_jobs: 1
    params:
      model_params.n_embd: choice(32, 64, 128, 256)
      model_params.n_layer: range(1, 3, step=1)
      model_params.n_head: choice(1, 2, 4)
      seqrec_module.lr: tag(log, interval(0.0003, 0.003))
      pdrop: choice(0.1, 0.3, 0.5)

seqrec_module:
  lr: 0.001
  predict_top_k: 10  
  filter_seen: True

trainer_params:
  max_epochs: 100
patience: 10

generation: False
mode: 'reciprocal_rank_aggregation'
generation_params:
  num_return_sequences: 1
  do_sample: False


evaluator:
  top_k: [10]
test_metrics: True