cuda_visible_devices: 0

project_name: sequential_recsys/generation_paper
task_name: GPT_train_predict
seed: 1337

data_path: ../data/ml-20m.csv
last_n_items: 10

dataset:
  max_length: 128
  shift_labels: False

dataloader:
  batch_size: 64
  test_batch_size: 16
  num_workers: 8
  validation_size: 10000

model: 'GPT-2'
model_params:
  n_positions: 128
  n_embd: 64
  n_layer: 2
  n_head: 1

seqrec_module:
  lr: 0.001
  predict_top_k: 10  # this value is used for validation
  filter_seen: True

trainer_params:
  max_epochs: 100
patience: 10

evaluator:
  top_k: [10]
test_metrics: True

generation: False