cuda_visible_devices: 0

project_name: sequential_recsys/generation_paper
task_name: SASRec_train_predict

data_path: ../data/ml-20m.csv
last_n_items: 10

dataset:
  max_length: 128

dataloader:
  batch_size: 64
  test_batch_size: 16
  num_workers: 8
  validation_size: 10000

model: 'SASRec'
model_params:
    maxlen: 128
    hidden_units: 64
    num_blocks: 2
    num_heads: 1
    dropout_rate: 0.1

seqrec_module:
  lr: 0.001
  predict_top_k: 10  # this value is used for validation
  filter_seen: True

trainer_params:
  max_epochs: 100
patience: 10

evaluator:
  top_k: [10]
test_metrics: True