defaults:
  - _self_
  - override hydra/sweeper: optuna
  - override hydra/sweeper/sampler: tpe

cuda_visible_devices: 1

project_name: sequential_recsys/generation_paper/hyper/${task_name}
task_name: SASRec_train_predict

data_path: ../data/ml-20m.csv
last_n_items: 10

optuna_metrics: val_ndcg@10

dataset:
  max_length: 128

dataloader:
  batch_size: 64
  test_batch_size: 16
  num_workers: 8
  validation_size: 10000

model: 'SASRec'
model_params:
    maxlen: ${dataset.max_length}
    hidden_units: 64
    num_blocks: 2
    num_heads: 1
    dropout_rate: 0.1

hydra:
  sweeper:
    sampler:
      _target_: optuna.samplers.TPESampler
    direction: maximize
    study_name: ${task_name}
    storage: "sqlite:///${task_name}.db"
    storage: 
    n_trials: 25
    n_jobs: 1
    params:
      model_params.hidden_units: choice(32, 64, 128, 256)
      model_params.num_blocks: range(1, 3, step=1)
      model_params.num_heads: choice(1, 2, 4)
      seqrec_module.lr: tag(log, interval(0.0003, 0.003))
      model_params.dropout_rate: choice(0.1, 0.3, 0.5)

seqrec_module:
  lr: 0.001
  predict_top_k: 10  # this value is used for validation
  filter_seen: True

trainer_params:
  max_epochs: 100
patience: 10

evaluator:
  top_k: [10]
test_metrics: False